print ("exemplo 1")
print (not True)
print (not False)
print ("exemplo 2")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("exemplo 3")
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print ('exercicio 05')
a=True
b=False
c=True
print(a and a)
print(b and b)
print(not c)
print(not a)
print(a and c)
print(a and b)
print(b and c)
print(a or c)
print(b or c)
print(c or a)
print(c or b)
print(c or c)
print(c or b)
print(a or b)
print (True or False and not True)
print ("exemplo 6")
salario=100
idade=20
print (salario>1000 and idade>18)
